name: CI Pipeline

on: 
push:  # SALAH: indentasi hilang
  branches: [ "main" ]
pull_request:  # SALAH: indentasi hilang
  branches: [ "main" ]

jobs:
build:  # SALAH: indentasi hilang
runs-on: ubuntu-latest  # SALAH: indentasi hilang
    
steps:
- name: Checkout Repository
uses: actions/checkout@v3  # SALAH: indentasi kurang
      
- name: Setup Python
uses: actions/setup-python@v4
with:  # SALAH: indentasi tidak konsisten
python-version: '3.10'  # SALAH: indentasi salah
        
- name: Install dependencies
run: pip install -r requirements.txt
      
- name: Run application
run: python app.py